# charts/platform/Chart.yaml
apiVersion: v2
name: platform
version: 1.0.0-next-2665bf6
dependencies:
  - name: alaffia
    version: 0.0.0
    repository: "file://../alaffia"
  - name: fdw
    version: 0.0.0
    repository: "file://../fdw"
  - name: reports
    version: 0.0.0
    repository: "file://../reports"
